version: "3"
services:
  host-app:
    image: host-app
    container_name: host-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - type: bind
        source: .
        target: /usr/src/app
      - type: volume
        source: node_modules
        target: /usr/src/app/host-app/node_modules
    networks:
      - microfrontends
    command: ["npm", "run", "dev"]
volumes:
  node_modules:
    name: host-app-node_modules
    driver: local
networks:
  microfrontends:
    external: true
